import express from 'express';
import cors from 'cors';
import morgan from 'morgan';
import dotenv from 'dotenv';

// Load environment variables for testing
dotenv.config({ path: '.env.test' });

// Initialize Sentry for testing
import { initSentry, requestHandler, tracingHandler, errorHandler, Sentry } from './sentry';
initSentry();

// Import routes
import authRoutes from './routes/auth.routes';
import userRoutes from './routes/user.routes';
import workoutRoutes from './routes/workout.routes';
import scheduleRoutes from './routes/schedule.routes';

// Initialize Express app
const app = express();

// Sentry middleware
app.use(requestHandler);
app.use(tracingHandler);

// Middleware
app.use(cors());
app.use(express.json());

// Logging in development
if (process.env.NODE_ENV !== 'test') {
  app.use(morgan('dev'));
}

// Routes
app.get('/', (req, res) => {
  res.json({ message: 'TFW MMA Lifting API' });
});

// API Routes
app.use('/api/auth', authRoutes);
app.use('/api/users', userRoutes);
app.use('/api/workouts', workoutRoutes);
app.use('/api/schedule', scheduleRoutes);

// Error test endpoint
app.post('/api/generate-503-error', (req, res, next) => {
  // Generate an actual error for testing
  const testError = new Error('Test 503 error generated by the error test page');
  testError.name = 'ServiceUnavailableError';
  
  // Manually capture with Sentry
  Sentry.captureException(testError, {
    tags: {
      test: true,
      endpoint: '/api/generate-503-error'
    }
  });
  
  res.status(503).json({
    error: 'Service Unavailable',
    message: 'This is a test 503 error generated by the error test page'
  });
});

// Sentry error handler
app.use(errorHandler);

// Error handling middleware
app.use((err: any, req: express.Request, res: express.Response, next: express.NextFunction) => {
  console.error(err.stack);
  res.status(500).json({
    error: 'Internal Server Error',
    message: process.env.NODE_ENV === 'development' ? err.message : undefined
  });
});

export { app };